# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest #ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QGIS 3.16.6
      uses: actions/setup-QGIS@v1
      with:
        QGIS-version: 3.16.6 #3.9
    - name: Set up Python 3.7.5 #Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5 #3.9
    - name: Install dependencies
      run: |
        QGIS restore
        python -m pip install --upgrade pip
        #pip install -U pywin32 
        pip install pywinauto
        pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Execute py script #Test with pywinauto #pytest
      run: |
        #pytest
        python Testplugin.py 
        #pip install pytest 
        #export PYTHONPATH = src 
        #pytest
